# File: .github/workflows/workflow.yml

on: 
  workflow_dispatch:
    inputs:
      parameter1:
        description: resource group name
        required: false

name: AzureCLISample

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL }}
    
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create --resource-group 12_MCW-RG --template-file ./Hands-on-Lab/templates/deploy-vm-as-domain-member1.json --parameters ./Hands-on-Lab/templates/deploy-vm-as-domain-member.parameters1.json

          
